#!/bin/sh
#
# Requires sway, grim, slurp and jq.

set -eo pipefail

: ${SCREENSHOT_HOME:="$HOME/screenshots"}
FILENAME="$SCREENSHOT_HOME/$(date -Ins).png"

mkdir -p $SCREENSHOT_HOME

if [ -z $1 ]; then
  # Full screen (current screen only)
  grim -o "$(swaymsg -t get_outputs | jq -r '.[] | select(.focused) | .name')" "$FILENAME"
elif [ $1 = "active" ]; then
  # Current window only
  ACTIVE="$(swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.focused) | .rect | "\(.x),\(.y) \(.width)x\(.height)"')"
  grim -g "$ACTIVE" "$FILENAME"
elif [ $1 = "region" ]; then
  # Specific region (manually selected)
  grim -g "$(slurp)" "$FILENAME"
elif [ $1 = "window" ]; then
  # Specific window (manually selected)
  WINDOW="$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp)"
  grim -g "$WINDOW" "$FILENAME"
elif [ $1 = "output" ]; then
  OUTPUT="$(swaymsg -t get_outputs | jq -r '.[] | select(.focused)' | jq -r '.name')"
  grim -o "$OUTPUT" "$FILENAME"
else
  cat << EOF
Usage: $(basename "$0") TARGET

Valid Targets:
  active: Currently active window.
  region: Manually select a region.
  window: Manually select a window.
  output: Currently active output.
EOF
  exit 0
fi;

echo "$FILENAME"

